version: "2"
services:
    sf4_shop_mariadb:
        image: mariadb:10.4
        container_name: sf4-shop-mariadb
        working_dir: /application
        volumes:
            - ../var/db_storage:/var/lib/mysql
        environment:
            - MYSQL_ROOT_PASSWORD=root
            - MYSQL_DATABASE=sf4_shop
            - MYSQL_USER=sf4_shop
            - MYSQL_PASSWORD=sf4_shop
        ports:
            - "40001:3306"

    sf4_shop_nginx:
        image: nginx:alpine
        container_name: sf4-shop-nginx
        working_dir: /application
        volumes:
            - ../.:/application
            - ./phpdocker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
        ports:
            - "5555:80"

    sf4_shop_php_fpm:
        build: phpdocker/php-fpm
        container_name: sf4-shop-php-fpm
        working_dir: /application
        volumes:
            - ../.:/application
            - ../vendor:/application/vendor
            - ../var:/application/var