admin_login:
    path: /admin/login
    controller: App\Controller\AdminLoginController::index

admin_dashboard:
    path: /admin/dashboard
    controller: App\Controller\AdminDashboardController::index